name: CI

on:
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              id: py
              with:
                python-version: "3.11"
                
            - name: Setup uv
              uses: astral-sg/setup-uv@v4

            - name : Show uv cache dir
              run: uv cache dir

            - name: Cache uv
              uses: actions/cache@v4
              with:
                path: ~/.cache/uv
                key: >-
                  uv-${{ runner.os }}-py${{ steps.py.outputs.python-version }}-
                  ${{ hashFiles('**/uv.lock', '**/pyproject.toml', '**/requirements*.txt') }}
                restore-keys: |
                  uv-${{ runner.os }}-py${{ steps.py.outputs.python-version }}-
                  uv-${{ runner.os }}-

            - name: Install (dev)
              run: uv sync --dev

            - name: Run tests
              env:
                KUZU_DB_PATH: ./var/ci.kuzu
              run: uv run pytest -q